import { BarChart, Bar, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { buildLoadAnalysisRows, pickBestAnalysis } from '@/lib/loadDevelopmentAnalysis';

function HighlightCard({ title, row, metric }) {
  return <div className="rounded-xl border border-border bg-card p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-muted-foreground">{title}</p>{row ? <><p className="font-semibold text-sm mt-1">{row.label}</p><p className="text-lg font-bold text-primary">{metric(row)}</p></> : <p className="text-sm text-muted-foreground mt-2">Not enough data</p>}</div>;
}

function MiniChart({ title, dataKey, rows, suffix = '' }) {
  const data = rows.filter((row) => row[dataKey] !== null).map((row) => ({ name: row.axis, value: row[dataKey] }));
  return <div className="rounded-xl border border-border bg-card p-3"><p className="text-sm font-semibold mb-3">{title}</p>{data.length === 0 ? <p className="text-sm text-muted-foreground">No comparable data yet.</p> : <div className="h-48"><ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip formatter={(value) => [`${value}${suffix}`, title]} /><Bar dataKey="value" fill="hsl(var(--primary))" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div>}</div>;
}

export default function LoadDevelopmentAnalysis({ test, variants, results }) {
  const rows = buildLoadAnalysisRows(test, variants, results);
  const best = pickBestAnalysis(rows);
  const complete = rows.filter((row) => row.complete).length;

  return <div className="space-y-4"><div className="rounded-xl border border-border bg-card p-4"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">Analysis</h2><p className="text-sm text-muted-foreground mt-1">Calculated from tested variants only. SD highlights use comparable Sample SD from included readings.</p></div><div className="text-right"><p className="text-2xl font-bold">{complete}/{rows.length}</p><p className="text-[10px] uppercase tracking-wide text-muted-foreground">complete</p></div></div></div><div className="grid grid-cols-2 md:grid-cols-5 gap-3"><HighlightCard title="Best Accuracy" row={best.bestAccuracy} metric={(row) => `${row.groupSize} MOA`} /><HighlightCard title="Lowest Sample SD" row={best.lowestComparableSd} metric={(row) => `${row.sd}`} /><HighlightCard title="Lowest ES" row={best.lowestEs} metric={(row) => `${row.es}`} /><HighlightCard title="Highest Avg Velocity" row={best.highestAvgVelocity} metric={(row) => `${row.avgVelocity} fps`} /><HighlightCard title="My Preferred Load" row={best.preferred} metric={() => 'Selected'} /></div><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><MiniChart title="Average Velocity" dataKey="avgVelocity" rows={rows} suffix=" fps" /><MiniChart title="Sample SD" dataKey="sd" rows={rows.filter((row) => row.sdComparable)} /><MiniChart title="Extreme Spread" dataKey="es" rows={rows} /><MiniChart title="Group Size" dataKey="groupSize" rows={rows} suffix=" MOA" /></div><div className="rounded-xl border border-border bg-card overflow-hidden"><div className="px-4 py-3 border-b border-border"><p className="font-semibold text-sm">Side-by-side comparison</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-xs text-muted-foreground"><tr><th className="text-left p-3">Variant</th><th className="text-left p-3">Data</th><th className="text-left p-3">Avg</th><th className="text-left p-3">SD</th><th className="text-left p-3">ES</th><th className="text-left p-3">Group</th></tr></thead><tbody>{rows.map((row) => <tr key={row.variant.id} className="border-t border-border"><td className="p-3 font-medium">{row.label}</td><td className="p-3">{row.complete ? `${row.includedReadings} readings` : 'Incomplete'}</td><td className="p-3">{row.avgVelocity ?? '—'}</td><td className="p-3">{row.sdComparable ? row.sd : '—'}</td><td className="p-3">{row.es ?? '—'}</td><td className="p-3">{row.groupSize ?? '—'}</td></tr>)}</tbody></table></div></div></div>;
}