import { jsPDF } from 'jspdf';
import { resolveClayClubName, buildClayScoreCardData, calculateDuration, normalizePhotos } from '@/lib/claySessionUtils';

const REPORT = {
  margin: 14,
  navy: [28, 48, 70],
  gunmetal: [48, 55, 64],
  copper: [196, 94, 18],
  text: [18, 24, 32],
  muted: [104, 112, 122],
  border: [210, 216, 224],
  soft: [245, 247, 250],
  white: [255, 255, 255],
};

function generateDocumentId() {
  const timestamp = Date.now().toString(36).toUpperCase();
  const random = Math.random().toString(36).substring(2, 8).toUpperCase();
  return `${timestamp}-${random}`;
}

function formatGeneratedDate(date = new Date()) {
  return `${date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })} ${date.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}`;
}

function formatDate(value) {
  if (!value) return 'Not recorded';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
}

function valueOrMissing(value) {
  if (value === null || value === undefined || value === '') return 'Not recorded';
  return String(value);
}

function getFullName(userInfo = {}) {
  return [userInfo.firstName, userInfo.middleName, userInfo.lastName].filter(Boolean).join(' ') || userInfo.full_name || userInfo.name || 'Not recorded';
}

function getAddress(userInfo = {}) {
  const parts = [userInfo.addressLine1, userInfo.addressLine2, userInfo.city, userInfo.postcode, userInfo.country].filter(Boolean);
  return parts.join(', ') || 'Not recorded';
}

async function getUserData(userInfo) {
  if (userInfo) return userInfo;
  try {
    const { base44 } = await import('@/api/base44Client');
    const authUser = await base44.auth.me();
    const fullUserData = await base44.entities.User.get(authUser.id);
    return {
      email: authUser.email,
      full_name: authUser.full_name,
      firstName: fullUserData.firstName || '',
      middleName: fullUserData.middleName || '',
      lastName: fullUserData.lastName || '',
      dateOfBirth: fullUserData.dateOfBirth || '',
      addressLine1: fullUserData.addressLine1 || '',
      addressLine2: fullUserData.addressLine2 || '',
      city: fullUserData.city || '',
      postcode: fullUserData.postcode || '',
      country: fullUserData.country || '',
    };
  } catch (error) {
    console.warn('Could not fetch user data for PDF:', error);
    return null;
  }
}

function categoryLabel(records = []) {
  const categories = new Set(records.map((record) => record.category || record.recordType));
  if (categories.size > 1) return 'Mixed Shooting Activities';
  const category = [...categories][0];
  if (category === 'clay_shooting' || category === 'clay') return 'Clay Shooting';
  if (category === 'target_shooting' || category === 'target') return 'Target Shooting';
  if (category === 'deer_management' || category === 'deer') return 'Deer Management';
  return 'Shooting Activity';
}

export function buildShootingReportData(records, userInfo, lookups = {}, documentId = generateDocumentId()) {
  const generatedAt = new Date();
  return {
    documentId,
    generatedAt,
    generatedAtLabel: formatGeneratedDate(generatedAt),
    category: categoryLabel(records),
    participant: {
      name: getFullName(userInfo || {}),
      email: valueOrMissing(userInfo?.email),
      dateOfBirth: userInfo?.dateOfBirth ? formatDate(userInfo.dateOfBirth) : 'Not recorded',
      address: getAddress(userInfo || {}),
    },
    records,
    lookups,
  };
}

function createDoc() {
  return new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
}

function pageMetrics(doc) {
  return { width: doc.internal.pageSize.getWidth(), height: doc.internal.pageSize.getHeight() };
}

function addReportFooter(doc, documentId) {
  const { width, height } = pageMetrics(doc);
  const totalPages = doc.getNumberOfPages();
  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page);
    doc.setDrawColor(...REPORT.border);
    doc.line(REPORT.margin, height - 13, width - REPORT.margin, height - 13);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(...REPORT.muted);
    doc.text('Generated by Shooting Records', REPORT.margin, height - 8);
    doc.text(`Doc ID: ${documentId}`, width / 2, height - 8, { align: 'center' });
    doc.text(`Page ${page} of ${totalPages}`, width - REPORT.margin, height - 8, { align: 'right' });
  }
}

function ensureSpace(doc, cursor, needed) {
  const { height } = pageMetrics(doc);
  if (cursor.y + needed <= height - 18) return cursor;
  doc.addPage();
  return { ...cursor, y: REPORT.margin };
}

function drawHeader(doc, reportData, cursor) {
  const { width } = pageMetrics(doc);
  doc.setFillColor(...REPORT.navy);
  doc.roundedRect(REPORT.margin, cursor.y, width - REPORT.margin * 2, 28, 2, 2, 'F');
  doc.setTextColor(...REPORT.white);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('SHOOTING ACTIVITY RECORD', REPORT.margin + 6, cursor.y + 11);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Official Regulatory Compliance Report', REPORT.margin + 6, cursor.y + 18);
  doc.setDrawColor(...REPORT.copper);
  doc.setLineWidth(1.2);
  doc.line(REPORT.margin + 6, cursor.y + 23, width - REPORT.margin - 6, cursor.y + 23);

  doc.setFontSize(8);
  doc.text(`Document ID: ${reportData.documentId}`, width - REPORT.margin - 6, cursor.y + 9, { align: 'right' });
  doc.text(`Generated: ${reportData.generatedAtLabel}`, width - REPORT.margin - 6, cursor.y + 15, { align: 'right' });
  doc.text(`Category: ${reportData.category}`, width - REPORT.margin - 6, cursor.y + 21, { align: 'right' });
  return { ...cursor, y: cursor.y + 36 };
}

function drawSectionTitle(doc, title, cursor) {
  const { width } = pageMetrics(doc);
  cursor = ensureSpace(doc, cursor, 16);
  doc.setFillColor(...REPORT.soft);
  doc.setDrawColor(...REPORT.border);
  doc.roundedRect(REPORT.margin, cursor.y, width - REPORT.margin * 2, 9, 1.5, 1.5, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setTextColor(...REPORT.navy);
  doc.text(title, REPORT.margin + 4, cursor.y + 6.1);
  return { ...cursor, y: cursor.y + 15 };
}

function drawInfoCard(doc, title, rows, cursor, options = {}) {
  const { width } = pageMetrics(doc);
  const cardX = options.x || REPORT.margin;
  const cardW = options.width || width - REPORT.margin * 2;
  const colCount = options.columns || 2;
  const rowHeight = options.rowHeight || 12;
  const titleHeight = title ? 10 : 0;
  const contentPadding = title ? 4 : 2;
  const rowsPerLine = Math.ceil(rows.length / colCount);
  const cardH = titleHeight + contentPadding + rowsPerLine * rowHeight + 7;
  cursor = ensureSpace(doc, cursor, cardH + 4);

  doc.setFillColor(...REPORT.white);
  doc.setDrawColor(...REPORT.border);
  doc.roundedRect(cardX, cursor.y, cardW, cardH, 2, 2, 'FD');

  let y = cursor.y + 6;
  if (title) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9.5);
    doc.setTextColor(...REPORT.navy);
    doc.text(title, cardX + 4, y);
    y += 7;
    doc.setDrawColor(...REPORT.border);
    doc.line(cardX + 4, y - 2, cardX + cardW - 4, y - 2);
    y += contentPadding;
  }

  const colW = (cardW - 8) / colCount;
  rows.forEach((row, index) => {
    const col = index % colCount;
    const line = Math.floor(index / colCount);
    const x = cardX + 4 + col * colW;
    const rowY = y + line * rowHeight;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(...REPORT.muted);
    doc.text(row.label, x, rowY + 1);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(...REPORT.text);
    const valueLines = doc.splitTextToSize(valueOrMissing(row.value), colW - 6);
    doc.text(valueLines.slice(0, 2), x, rowY + 6);
  });

  return { ...cursor, y: cursor.y + cardH + 6 };
}

function drawParticipantInfo(doc, reportData, cursor) {
  return drawInfoCard(doc, 'Participant Information', [
    { label: 'Name', value: reportData.participant.name },
    { label: 'Email', value: reportData.participant.email },
    { label: 'Date of Birth', value: reportData.participant.dateOfBirth },
    { label: 'Report Generated', value: reportData.generatedAtLabel },
    { label: 'Address', value: reportData.participant.address },
    { label: 'Document ID', value: reportData.documentId },
  ], cursor, { columns: 2, rowHeight: 14 });
}

function drawDataTable(doc, columns, rows, cursor, options = {}) {
  const { width } = pageMetrics(doc);
  const x = options.x || REPORT.margin;
  const providedWidths = options.widths;
  const tableW = options.width || (providedWidths ? providedWidths.reduce((sum, item) => sum + item, 0) : width - REPORT.margin * 2);
  const widths = providedWidths || columns.map(() => tableW / columns.length);
  const headerH = 9;
  const rowH = options.rowHeight || 9;
  cursor = ensureSpace(doc, cursor, headerH + rowH + 6);

  const drawHeader = () => {
    doc.setFillColor(...REPORT.soft);
    doc.setDrawColor(155, 164, 176);
    doc.setLineWidth(0.35);
    doc.rect(x, cursor.y, tableW, headerH, 'FD');
    let colX = x;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(options.fontSize || 8.5);
    doc.setTextColor(...REPORT.gunmetal);
    columns.forEach((column, index) => {
      doc.line(colX, cursor.y, colX, cursor.y + headerH);
      doc.text(column, colX + widths[index] / 2, cursor.y + 6, { align: 'center' });
      colX += widths[index];
    });
    doc.line(colX, cursor.y, colX, cursor.y + headerH);
    cursor.y += headerH;
  };

  drawHeader();
  rows.forEach((row) => {
    cursor = ensureSpace(doc, cursor, rowH + 8);
    let colX = x;
    doc.setDrawColor(155, 164, 176);
    doc.setLineWidth(0.35);
    doc.rect(x, cursor.y, tableW, rowH);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(options.fontSize || 8.5);
    doc.setTextColor(...REPORT.text);
    row.forEach((cell, index) => {
      doc.line(colX, cursor.y, colX, cursor.y + rowH);
      const align = options.leftColumns?.includes(index) ? 'left' : 'center';
      const textX = align === 'left' ? colX + 3 : colX + widths[index] / 2;
      const text = doc.splitTextToSize(valueOrMissing(cell), widths[index] - 6)[0] || 'Not recorded';
      doc.text(text, textX, cursor.y + 6, { align });
      colX += widths[index];
    });
    doc.line(colX, cursor.y, colX, cursor.y + rowH);
    cursor.y += rowH;
  });

  return { ...cursor, y: cursor.y + 5 };
}

function buildClayReportData(record, reportData) {
  const { shotguns = {}, clubs = {}, locations = {}, clayData = {} } = reportData.lookups;
  const shotgun = shotguns[record.shotgun_id] || {};
  const scorecard = clayData.scorecards?.[record.id];
  const stands = clayData.stands?.[record.id] || [];
  const shots = clayData.shots?.[record.id] || {};
  const scoreData = buildClayScoreCardData(record, scorecard, stands, shots);
  return {
    clubName: resolveClayClubName(record, clubs, locations),
    duration: calculateDuration(record.checkin_time || record.start_time, record.checkout_time || record.end_time),
    shotgun,
    scoreData,
    photos: normalizePhotos(record.photos || []),
  };
}

function drawClayReportHeader(doc, reportData, cursor) {
  const { width } = pageMetrics(doc);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...REPORT.navy);
  doc.text('CLAY SHOOTING SESSION REPORT', REPORT.margin, cursor.y + 6);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(...REPORT.muted);
  doc.text('Detailed Activity Record', REPORT.margin, cursor.y + 13);

  doc.setFontSize(8);
  doc.text(`Document ID: ${reportData.documentId}`, width - REPORT.margin, cursor.y + 6, { align: 'right' });
  doc.text(`Generated: ${reportData.generatedAtLabel}`, width - REPORT.margin, cursor.y + 12, { align: 'right' });

  doc.setDrawColor(...REPORT.copper);
  doc.setLineWidth(0.8);
  doc.line(REPORT.margin, cursor.y + 19, width - REPORT.margin, cursor.y + 19);
  return { ...cursor, y: cursor.y + 28 };
}

function drawClayPageTitle(doc, title, cursor, reportData = null) {
  const { width } = pageMetrics(doc);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...REPORT.navy);
  doc.text(title, REPORT.margin, cursor.y + 6);
  if (reportData) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...REPORT.muted);
    doc.text(`Document ID: ${reportData.documentId}`, width - REPORT.margin, cursor.y + 5, { align: 'right' });
    doc.text(`Generated: ${reportData.generatedAtLabel}`, width - REPORT.margin, cursor.y + 11, { align: 'right' });
  }
  doc.setDrawColor(...REPORT.copper);
  doc.setLineWidth(0.8);
  doc.line(REPORT.margin, cursor.y + 14, width - REPORT.margin, cursor.y + 14);
  return { ...cursor, y: cursor.y + 24 };
}

function drawClayCompactCard(doc, title, rows, cursor) {
  const { width } = pageMetrics(doc);
  const cardW = width - REPORT.margin * 2;
  const colW = (cardW - 10) / 2;
  const rowHeight = 8;
  const rowsPerLine = Math.ceil(rows.length / 2);
  const cardH = 10 + rowsPerLine * rowHeight + 4;
  cursor = ensureSpace(doc, cursor, cardH + 4);

  doc.setFillColor(...REPORT.white);
  doc.setDrawColor(...REPORT.border);
  doc.roundedRect(REPORT.margin, cursor.y, cardW, cardH, 1.5, 1.5, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...REPORT.navy);
  doc.text(title, REPORT.margin + 4, cursor.y + 6.5);
  doc.setDrawColor(...REPORT.border);
  doc.line(REPORT.margin + 4, cursor.y + 9, width - REPORT.margin - 4, cursor.y + 9);

  rows.forEach((row, index) => {
    const col = index % 2;
    const line = Math.floor(index / 2);
    const x = REPORT.margin + 4 + col * colW;
    const y = cursor.y + 15 + line * rowHeight;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.2);
    doc.setTextColor(...REPORT.muted);
    doc.text(`${row.label}:`, x, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.7);
    doc.setTextColor(...REPORT.text);
    const labelWidth = doc.getTextWidth(`${row.label}: `);
    const valueLines = doc.splitTextToSize(valueOrMissing(row.value), colW - labelWidth - 8);
    doc.text(valueLines[0] || 'Not Recorded', x + labelWidth + 1.5, y);
  });

  return { ...cursor, y: cursor.y + cardH + 4 };
}

function renderClaySession(doc, record, reportData, cursor, options = {}) {
  const data = buildClayReportData(record, reportData);
  if (options.includeTitle !== false) {
    cursor = drawSectionTitle(doc, 'CLAY SHOOTING SESSION REPORT', cursor);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(...REPORT.muted);
    doc.text('Detailed Activity Record', REPORT.margin + 2, cursor.y - 5);
  }

  cursor = drawClayCompactCard(doc, 'Session Overview', [
    { label: 'Session Date', value: formatDate(record.date) },
    { label: 'Session Type', value: 'Clay Shooting' },
    { label: 'Club / Range', value: data.clubName },
    { label: 'Duration', value: data.duration || 'Not Recorded' },
    { label: 'Check-In', value: record.checkin_time || record.start_time || 'Not Recorded' },
    { label: 'Check-Out', value: record.checkout_time || record.end_time || 'Not Recorded' },
  ], cursor);

  cursor = drawClayCompactCard(doc, 'Shotgun Used', [
    { label: 'Name', value: data.shotgun.name },
    { label: 'Make', value: data.shotgun.make },
    { label: 'Model', value: data.shotgun.model },
    { label: 'Gauge', value: data.shotgun.gauge },
    { label: 'Serial', value: data.shotgun.serial_number },
    { label: 'Cartridges Fired', value: record.rounds_fired || 0 },
  ], cursor);

  cursor = drawClayCompactCard(doc, 'Cartridges / Ammunition', [
    { label: 'Brand / Name', value: record.ammunition_used },
    { label: 'Gauge', value: data.shotgun.gauge },
    { label: 'Quantity Used', value: record.rounds_fired || 0 },
    { label: 'Shot Size', value: record.shot_size },
    { label: 'Load / Weight', value: record.load_grams || record.grams },
    { label: 'Cost', value: record.cost || record.total_cost },
  ], cursor);

  if (options.separateScoreAndPhotos) {
    doc.addPage();
    cursor = drawClayPageTitle(doc, 'SCORE CARD', { y: REPORT.margin }, reportData);
  } else {
    cursor = ensureSpace(doc, cursor, data.photos.length === 0 ? 58 : 78);
    cursor = drawSectionTitle(doc, 'Score Card', cursor);
  }
  if (!data.scoreData) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(...REPORT.text);
    doc.text('No Score Card Recorded', REPORT.margin + 4, cursor.y);
    cursor.y += 10;
  } else {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(...REPORT.navy);
    doc.text('Score Summary', REPORT.margin + 2, cursor.y);
    cursor.y += 4;
    cursor = drawDataTable(doc, ['Total Targets', 'Hits', 'Missed', 'Percentage'], [[
      data.scoreData.totalTargets,
      data.scoreData.hits,
      data.scoreData.missed,
      `${data.scoreData.percentage}%`,
    ]], cursor, { widths: [52, 36, 36, 52], fontSize: 8.3, rowHeight: 9 });

    if (data.scoreData.stands.length > 0) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(...REPORT.navy);
      doc.text('Stand Breakdown', REPORT.margin + 2, cursor.y);
      cursor.y += 4;
      cursor = drawDataTable(
        doc,
        ['Stand', 'Discipline', 'Targets', 'Hits', 'Missed', 'Score'],
        data.scoreData.stands.map((stand) => [stand.standNumber, stand.discipline, stand.targets, stand.hits, stand.missed, `${stand.hits}/${stand.targets}`]),
        cursor,
        { widths: [18, 54, 28, 22, 26, 30], leftColumns: [1], rowHeight: 9, fontSize: 8.3 }
      );
    }
  }

  if (options.separateScoreAndPhotos) {
    doc.addPage();
    cursor = drawClayPageTitle(doc, 'PHOTOS', { y: REPORT.margin }, reportData);
    cursor = drawPhotosSection(doc, data.photos, cursor, null);
  } else {
    cursor = drawPhotosSection(doc, data.photos, cursor, 'Photos');
    if (record.notes) cursor = drawNotes(doc, record.notes, cursor);
  }
  return cursor;
}

function renderTargetSession(doc, record, reportData, cursor) {
  const { rifles = {}, clubs = {}, targetGroups = [] } = reportData.lookups;
  const clubName = record.club_name || (record.club_id && clubs[record.club_id]?.name) || record.location_name || record.range_name || record.place_name || 'Not recorded';
  cursor = drawSectionTitle(doc, 'TARGET SHOOTING SESSION REPORT', cursor);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...REPORT.muted);
  doc.text('Detailed Activity Record', REPORT.margin + 2, cursor.y - 5);

  cursor = drawInfoCard(doc, 'Session Overview', [
    { label: 'Session Date', value: formatDate(record.date) },
    { label: 'Session Type', value: 'Target Shooting' },
    { label: 'Club / Range', value: clubName },
    { label: 'Check-in', value: record.checkin_time },
    { label: 'Check-out', value: record.checkout_time },
  ], cursor, { columns: 2, rowHeight: 14 });

  if (record.rifles_used?.length) {
    cursor = drawSectionTitle(doc, 'FIREARMS & AMMUNITION', cursor);
    cursor = drawDataTable(doc, ['Firearm', 'Calibre', 'Rounds', 'Range', 'Ammunition', 'Bullet'], record.rifles_used.map((rifle) => {
      const rifleData = rifles[rifle.rifle_id] || {};
      return [
        rifleData.name || rifle.rifle_name || 'Not recorded',
        rifle.caliber || rifleData.caliber || 'Not recorded',
        rifle.rounds_fired || 0,
        rifle.meters_range ? `${rifle.meters_range}m` : 'Not recorded',
        rifle.ammunition_brand || 'Not recorded',
        [rifle.bullet_type, rifle.grain].filter(Boolean).join(' / ') || 'Not recorded',
      ];
    }), cursor, { widths: [35, 25, 20, 22, 45, 39], leftColumns: [0, 4, 5], rowHeight: 9 });
  }

  const groups = targetGroups.filter((group) => group.session_id === record.id);
  if (groups.length > 0) {
    cursor = drawSectionTitle(doc, 'TARGET ANALYSIS RESULTS', cursor);
    cursor = drawDataTable(doc, ['Group', 'Shots', 'Distance', 'MOA', 'Size mm', 'MRAD'], groups.map((group, index) => [
      group.group_name || `Group ${index + 1}`,
      group.number_of_shots || 'Not recorded',
      group.distance_override ? `${group.distance_override}m` : 'Not recorded',
      group.group_size_moa ? group.group_size_moa.toFixed(2) : 'Not recorded',
      group.group_size_mm || 'Not recorded',
      group.group_size_mrad ? group.group_size_mrad.toFixed(3) : 'Not recorded',
    ]), cursor, { widths: [42, 22, 28, 28, 30, 30], leftColumns: [0] });
  }

  cursor = drawPhotosSection(doc, normalizePhotos(record.photos || []), cursor, 'TARGET PHOTOS');
  if (record.notes) cursor = drawNotes(doc, record.notes, cursor);
  return cursor;
}

function drawPhotosSection(doc, photos, cursor, title = 'PHOTOS') {
  if (title) cursor = drawSectionTitle(doc, title, cursor);
  if (!photos.length) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(...REPORT.text);
    doc.text('No Photos Recorded', REPORT.margin + 4, cursor.y);
    return { ...cursor, y: cursor.y + 10 };
  }

  const photoW = 40;
  const photoH = 30;
  const gap = 6;
  let x = REPORT.margin + 4;
  photos.forEach((photoUrl, index) => {
    cursor = ensureSpace(doc, cursor, photoH + 12);
    const { width } = pageMetrics(doc);
    if (x + photoW > width - REPORT.margin) {
      x = REPORT.margin + 4;
      cursor.y += photoH + 10;
      cursor = ensureSpace(doc, cursor, photoH + 12);
    }
    try {
      doc.addImage(photoUrl, 'JPEG', x, cursor.y, photoW, photoH);
      doc.link(x, cursor.y, photoW, photoH, { url: photoUrl });
    } catch (error) {
      doc.setDrawColor(...REPORT.border);
      doc.rect(x, cursor.y, photoW, photoH);
      doc.setFontSize(7);
      doc.setTextColor(...REPORT.muted);
      doc.text('Image unavailable', x + 5, cursor.y + 16);
    }
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(...REPORT.muted);
    doc.text(`Photo ${index + 1}`, x, cursor.y + photoH + 5);
    x += photoW + gap;
  });
  return { ...cursor, y: cursor.y + photoH + 13 };
}

function drawNotes(doc, notes, cursor) {
  cursor = drawSectionTitle(doc, 'NOTES', cursor);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...REPORT.text);
  doc.splitTextToSize(notes, pageMetrics(doc).width - REPORT.margin * 2 - 8).forEach((line) => {
    cursor = ensureSpace(doc, cursor, 6);
    doc.text(line, REPORT.margin + 4, cursor.y);
    cursor.y += 5;
  });
  return { ...cursor, y: cursor.y + 4 };
}

function renderDeerSession(doc, record, reportData, cursor) {
  cursor = drawSectionTitle(doc, 'DEER MANAGEMENT SESSION REPORT', cursor);
  cursor = drawInfoCard(doc, 'Session Overview', [
    { label: 'Session Date', value: formatDate(record.date) },
    { label: 'Session Type', value: 'Deer Management' },
    { label: 'Location', value: record.location_name || record.place_name },
    { label: 'Start Time', value: record.start_time },
    { label: 'End Time', value: record.end_time },
    { label: 'Total Count', value: record.total_count || record.number_shot || 0 },
  ], cursor, { columns: 2, rowHeight: 14 });
  cursor = drawPhotosSection(doc, normalizePhotos(record.photos || []), cursor);
  if (record.notes) cursor = drawNotes(doc, record.notes, cursor);
  return cursor;
}

function renderRecords(doc, reportData) {
  let cursor = { y: REPORT.margin };
  const isClayOnly = reportData.records.length > 0 && reportData.records.every((record) => record.category === 'clay_shooting' || record.recordType === 'clay');

  if (isClayOnly) {
    cursor = drawClayReportHeader(doc, reportData, cursor);
  } else {
    cursor = drawHeader(doc, reportData, cursor);
    cursor = drawParticipantInfo(doc, reportData, cursor);
  }

  reportData.records.forEach((record, index) => {
    cursor = ensureSpace(doc, cursor, index === 0 ? 30 : 55);
    if (index > 0 && cursor.y > 220) {
      doc.addPage();
      cursor = { y: REPORT.margin };
      if (isClayOnly) cursor = drawClayReportHeader(doc, reportData, cursor);
    }
    if (record.category === 'clay_shooting' || record.recordType === 'clay') {
      cursor = renderClaySession(doc, record, reportData, cursor, { includeTitle: !isClayOnly, separateScoreAndPhotos: isClayOnly });
    } else if (record.category === 'target_shooting' || record.recordType === 'target') {
      cursor = renderTargetSession(doc, record, reportData, cursor);
    } else if (record.category === 'deer_management' || record.recordType === 'deer') {
      cursor = renderDeerSession(doc, record, reportData, cursor);
    }
  });
}

export async function exportProfessionalRecordsToPdf(records, userInfo = null, fileName = 'shooting-records.pdf', rifles = {}, clubs = {}, shotguns = {}, locations = {}, targetGroups = [], clayData = {}) {
  const userData = await getUserData(userInfo);
  const documentId = generateDocumentId();
  const reportData = buildShootingReportData(records, userData, { rifles, clubs, shotguns, locations, targetGroups, clayData }, documentId);
  const doc = createDoc();
  renderRecords(doc, reportData);
  addReportFooter(doc, documentId);
  doc.save(fileName);
}

export async function getProfessionalRecordsPdfBlob(records, userInfo = null, rifles = {}, clubs = {}, shotguns = {}, locations = {}, targetGroups = [], clayData = {}) {
  const userData = await getUserData(userInfo);
  const documentId = generateDocumentId();
  const reportData = buildShootingReportData(records, userData, { rifles, clubs, shotguns, locations, targetGroups, clayData }, documentId);
  const doc = createDoc();
  renderRecords(doc, reportData);
  addReportFooter(doc, documentId);
  return doc.output('blob');
}