import { jsPDF } from 'jspdf';
import { resolveClayClubName, buildClayScoreCardData, calculateDuration, normalizePhotos } from '@/lib/claySessionUtils';

const REPORT = {
  margin: 14,
  navy: [28, 48, 70],
  gunmetal: [48, 55, 64],
  copper: [196, 94, 18],
  text: [18, 24, 32],
  muted: [104, 112, 122],
  border: [210, 216, 224],
  soft: [245, 247, 250],
  white: [255, 255, 255],
};

function generateDocumentId() {
  const timestamp = Date.now().toString(36).toUpperCase();
  const random = Math.random().toString(36).substring(2, 8).toUpperCase();
  return `${timestamp}-${random}`;
}

function formatGeneratedDate(date = new Date()) {
  return `${date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })} ${date.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}`;
}

function formatDate(value) {
  if (!value) return 'Not recorded';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
}

function valueOrMissing(value) {
  if (value === null || value === undefined || value === '') return 'Not recorded';
  return String(value);
}

function getFullName(userInfo = {}) {
  return [userInfo.firstName, userInfo.middleName, userInfo.lastName].filter(Boolean).join(' ') || userInfo.full_name || userInfo.name || 'Not recorded';
}

function getAddress(userInfo = {}) {
  const parts = [userInfo.addressLine1, userInfo.addressLine2, userInfo.city, userInfo.postcode, userInfo.country].filter(Boolean);
  return parts.join(', ') || 'Not recorded';
}

async function getUserData(userInfo) {
  if (userInfo) return userInfo;
  try {
    const { base44 } = await import('@/api/base44Client');
    const authUser = await base44.auth.me();
    const fullUserData = await base44.entities.User.get(authUser.id);
    return {
      email: authUser.email,
      full_name: authUser.full_name,
      firstName: fullUserData.firstName || '',
      middleName: fullUserData.middleName || '',
      lastName: fullUserData.lastName || '',
      dateOfBirth: fullUserData.dateOfBirth || '',
      addressLine1: fullUserData.addressLine1 || '',
      addressLine2: fullUserData.addressLine2 || '',
      city: fullUserData.city || '',
      postcode: fullUserData.postcode || '',
      country: fullUserData.country || '',
    };
  } catch (error) {
    console.warn('Could not fetch user data for PDF:', error);
    return null;
  }
}

function categoryLabel(records = []) {
  const categories = new Set(records.map((record) => record.category || record.recordType));
  if (categories.size > 1) return 'Mixed Shooting Activities';
  const category = [...categories][0];
  if (category === 'clay_shooting' || category === 'clay') return 'Clay Shooting';
  if (category === 'target_shooting' || category === 'target') return 'Target Shooting';
  if (category === 'deer_management' || category === 'deer') return 'Deer Management';
  return 'Shooting Activity';
}

export function buildShootingReportData(records, userInfo, lookups = {}, documentId = generateDocumentId()) {
  const generatedAt = new Date();
  return {
    documentId,
    generatedAt,
    generatedAtLabel: formatGeneratedDate(generatedAt),
    category: categoryLabel(records),
    participant: {
      name: getFullName(userInfo || {}),
      email: valueOrMissing(userInfo?.email),
      dateOfBirth: userInfo?.dateOfBirth ? formatDate(userInfo.dateOfBirth) : 'Not recorded',
      address: getAddress(userInfo || {}),
    },
    records,
    lookups,
  };
}

function createDoc() {
  return new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
}

function pageMetrics(doc) {
  return { width: doc.internal.pageSize.getWidth(), height: doc.internal.pageSize.getHeight() };
}

function addReportFooter(doc, documentId, generatedAtLabel = null) {
  const { width, height } = pageMetrics(doc);
  const totalPages = doc.getNumberOfPages();
  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page);
    doc.setDrawColor(...REPORT.border);
    doc.line(REPORT.margin, height - 13, width - REPORT.margin, height - 13);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.2);
    doc.setTextColor(...REPORT.muted);
    const footerText = `Generated by Shooting Records | Doc ID: ${documentId} | Page ${page} of ${totalPages}`;
    doc.text(footerText, width / 2, height - 8, { align: 'center' });
  }
}

function ensureSpace(doc, cursor, needed) {
  const { height } = pageMetrics(doc);
  if (cursor.y + needed <= height - 18) return cursor;
  doc.addPage();
  return { ...cursor, y: REPORT.margin };
}

function drawHeader(doc, reportData, cursor) {
  const { width } = pageMetrics(doc);
  doc.setFillColor(...REPORT.navy);
  doc.roundedRect(REPORT.margin, cursor.y, width - REPORT.margin * 2, 28, 2, 2, 'F');
  doc.setTextColor(...REPORT.white);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('SHOOTING ACTIVITY RECORD', REPORT.margin + 6, cursor.y + 11);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Official Regulatory Compliance Report', REPORT.margin + 6, cursor.y + 18);
  doc.setDrawColor(...REPORT.copper);
  doc.setLineWidth(1.2);
  doc.line(REPORT.margin + 6, cursor.y + 23, width - REPORT.margin - 6, cursor.y + 23);

  doc.setFontSize(8);
  doc.text(`Document ID: ${reportData.documentId}`, width - REPORT.margin - 6, cursor.y + 9, { align: 'right' });
  doc.text(`Generated: ${reportData.generatedAtLabel}`, width - REPORT.margin - 6, cursor.y + 15, { align: 'right' });
  doc.text(`Category: ${reportData.category}`, width - REPORT.margin - 6, cursor.y + 21, { align: 'right' });
  return { ...cursor, y: cursor.y + 36 };
}

function drawSectionTitle(doc, title, cursor) {
  const { width } = pageMetrics(doc);
  cursor = ensureSpace(doc, cursor, 16);
  doc.setFillColor(...REPORT.soft);
  doc.setDrawColor(...REPORT.border);
  doc.roundedRect(REPORT.margin, cursor.y, width - REPORT.margin * 2, 9, 1.5, 1.5, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setTextColor(...REPORT.navy);
  doc.text(title, REPORT.margin + 4, cursor.y + 6.1);
  return { ...cursor, y: cursor.y + 15 };
}

function drawInfoCard(doc, title, rows, cursor, options = {}) {
  const { width } = pageMetrics(doc);
  const cardX = options.x || REPORT.margin;
  const cardW = options.width || width - REPORT.margin * 2;
  const colCount = options.columns || 2;
  const rowHeight = options.rowHeight || 12;
  const titleHeight = title ? 10 : 0;
  const contentPadding = title ? 4 : 2;
  const rowsPerLine = Math.ceil(rows.length / colCount);
  const cardH = titleHeight + contentPadding + rowsPerLine * rowHeight + 7;
  cursor = ensureSpace(doc, cursor, cardH + 4);

  doc.setFillColor(...REPORT.white);
  doc.setDrawColor(...REPORT.border);
  doc.roundedRect(cardX, cursor.y, cardW, cardH, 2, 2, 'FD');

  let y = cursor.y + 6;
  if (title) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9.5);
    doc.setTextColor(...REPORT.navy);
    doc.text(title, cardX + 4, y);
    y += 7;
    doc.setDrawColor(...REPORT.border);
    doc.line(cardX + 4, y - 2, cardX + cardW - 4, y - 2);
    y += contentPadding;
  }

  const colW = (cardW - 8) / colCount;
  rows.forEach((row, index) => {
    const col = index % colCount;
    const line = Math.floor(index / colCount);
    const x = cardX + 4 + col * colW;
    const rowY = y + line * rowHeight;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(...REPORT.muted);
    doc.text(row.label, x, rowY + 1);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(...REPORT.text);
    const valueLines = doc.splitTextToSize(valueOrMissing(row.value), colW - 6);
    doc.text(valueLines.slice(0, 2), x, rowY + 6);
  });

  return { ...cursor, y: cursor.y + cardH + 6 };
}

function drawParticipantInfo(doc, reportData, cursor) {
  return drawInfoCard(doc, 'Participant Information', [
    { label: 'Name', value: reportData.participant.name },
    { label: 'Email', value: reportData.participant.email },
    { label: 'Date of Birth', value: reportData.participant.dateOfBirth },
    { label: 'Report Generated', value: reportData.generatedAtLabel },
    { label: 'Address', value: reportData.participant.address },
    { label: 'Document ID', value: reportData.documentId },
  ], cursor, { columns: 2, rowHeight: 14 });
}

function drawDataTable(doc, columns, rows, cursor, options = {}) {
  const { width } = pageMetrics(doc);
  const x = options.x || REPORT.margin;
  const providedWidths = options.widths;
  const tableW = options.width || (providedWidths ? providedWidths.reduce((sum, item) => sum + item, 0) : width - REPORT.margin * 2);
  const widths = providedWidths || columns.map(() => tableW / columns.length);
  const headerH = 9;
  const rowH = options.rowHeight || 9;
  cursor = ensureSpace(doc, cursor, headerH + rowH + 6);

  const drawHeader = () => {
    doc.setFillColor(...REPORT.soft);
    doc.setDrawColor(...(options.borderColor || REPORT.border));
    doc.setLineWidth(options.lineWidth || 0.2);
    doc.rect(x, cursor.y, tableW, headerH, 'FD');
    let colX = x;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(options.fontSize || 8.5);
    doc.setTextColor(...REPORT.gunmetal);
    columns.forEach((column, index) => {
      doc.line(colX, cursor.y, colX, cursor.y + headerH);
      doc.text(column, colX + widths[index] / 2, cursor.y + 6, { align: 'center' });
      colX += widths[index];
    });
    doc.line(colX, cursor.y, colX, cursor.y + headerH);
    cursor.y += headerH;
  };

  drawHeader();
  rows.forEach((row) => {
    cursor = ensureSpace(doc, cursor, rowH + 8);
    let colX = x;
    doc.setDrawColor(...(options.borderColor || REPORT.border));
    doc.setLineWidth(options.lineWidth || 0.2);
    doc.rect(x, cursor.y, tableW, rowH);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(options.fontSize || 8.5);
    doc.setTextColor(...REPORT.text);
    row.forEach((cell, index) => {
      doc.line(colX, cursor.y, colX, cursor.y + rowH);
      const align = options.leftColumns?.includes(index) ? 'left' : 'center';
      const textX = align === 'left' ? colX + 3 : colX + widths[index] / 2;
      const text = doc.splitTextToSize(valueOrMissing(cell), widths[index] - 6)[0] || 'Not recorded';
      doc.text(text, textX, cursor.y + 6, { align });
      colX += widths[index];
    });
    doc.line(colX, cursor.y, colX, cursor.y + rowH);
    cursor.y += rowH;
  });

  return { ...cursor, y: cursor.y + 5 };
}

function buildClayReportData(record, reportData) {
  const { shotguns = {}, clubs = {}, locations = {}, clayData = {} } = reportData.lookups;
  const shotgun = shotguns[record.shotgun_id] || {};
  const scorecard = clayData.scorecards?.[record.id];
  const stands = clayData.stands?.[record.id] || [];
  const shots = clayData.shots?.[record.id] || {};
  const scoreData = buildClayScoreCardData(record, scorecard, stands, shots);
  return {
    clubName: resolveClayClubName(record, clubs, locations),
    duration: calculateDuration(record.checkin_time || record.start_time, record.checkout_time || record.end_time),
    shotgun,
    scoreData,
    photos: normalizePhotos(record.photos || []),
  };
}

function resolveTargetClubName(record, clubs = {}, locations = {}) {
  return record.club_name
    || record.range_name
    || record.location_name
    || record.place_name
    || record.venue_name
    || (record.club_id && clubs[record.club_id]?.name)
    || (record.location_id && (clubs[record.location_id]?.name || locations[record.location_id]?.name || locations[record.location_id]?.place_name))
    || 'Not Recorded';
}

function getTargetGroupPhoto(group = {}) {
  const photos = normalizePhotos(group.photos || []);
  return group.photo_url || group.target_photo_url || group.image_url || group.target_photo || photos[0] || null;
}

function buildTargetReportData(record, reportData) {
  const { rifles = {}, clubs = {}, locations = {}, targetGroups = [] } = reportData.lookups;
  const groups = targetGroups.filter((group) => group.session_id === record.id || group.session_record_id === record.id || group.target_session_id === record.id);
  return {
    clubName: resolveTargetClubName(record, clubs, locations),
    duration: calculateDuration(record.checkin_time || record.start_time, record.checkout_time || record.end_time),
    rifles,
    groups,
    photos: normalizePhotos(record.photos || []),
  };
}

function drawClayReportHeader(doc, reportData, cursor) {
  const { width } = pageMetrics(doc);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...REPORT.navy);
  doc.text('CLAY SHOOTING SESSION REPORT', REPORT.margin, cursor.y + 6);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(...REPORT.muted);
  doc.text('Detailed Activity Record', REPORT.margin, cursor.y + 13);

  doc.setFontSize(8);
  doc.text(`Document ID: ${reportData.documentId}`, REPORT.margin, cursor.y + 19);
  doc.text(`Generated: ${reportData.generatedAtLabel}`, REPORT.margin, cursor.y + 24);

  doc.setDrawColor(...REPORT.copper);
  doc.setLineWidth(0.8);
  doc.line(REPORT.margin, cursor.y + 29, width - REPORT.margin, cursor.y + 29);
  return { ...cursor, y: cursor.y + 38 };
}

function drawTargetReportHeader(doc, reportData, cursor) {
  const { width } = pageMetrics(doc);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...REPORT.navy);
  doc.text('TARGET SHOOTING SESSION REPORT', REPORT.margin, cursor.y + 6);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(...REPORT.muted);
  doc.text('Detailed Activity Record', REPORT.margin, cursor.y + 13);

  doc.setFontSize(8);
  doc.text(`Document ID: ${reportData.documentId}`, REPORT.margin, cursor.y + 19);
  doc.text(`Generated: ${reportData.generatedAtLabel}`, REPORT.margin, cursor.y + 24);

  doc.setDrawColor(...REPORT.copper);
  doc.setLineWidth(0.8);
  doc.line(REPORT.margin, cursor.y + 29, width - REPORT.margin, cursor.y + 29);
  return { ...cursor, y: cursor.y + 38 };
}

function drawClayPageTitle(doc, title, cursor, reportData = null) {
  const { width } = pageMetrics(doc);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...REPORT.navy);
  doc.text(title, REPORT.margin, cursor.y + 6);
  if (reportData) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...REPORT.muted);
    doc.text(`Document ID: ${reportData.documentId}`, REPORT.margin, cursor.y + 13);
    doc.text(`Generated: ${reportData.generatedAtLabel}`, REPORT.margin, cursor.y + 18);
  }
  doc.setDrawColor(...REPORT.copper);
  doc.setLineWidth(0.8);
  doc.line(REPORT.margin, cursor.y + 23, width - REPORT.margin, cursor.y + 23);
  return { ...cursor, y: cursor.y + 32 };
}

function drawClayCompactCard(doc, title, rows, cursor) {
  const { width } = pageMetrics(doc);
  const cardW = width - REPORT.margin * 2;
  const colW = (cardW - 10) / 2;
  const rowHeight = 8;
  const rowsPerLine = Math.ceil(rows.length / 2);
  const cardH = 10 + rowsPerLine * rowHeight + 4;
  cursor = ensureSpace(doc, cursor, cardH + 4);

  doc.setFillColor(...REPORT.white);
  doc.setDrawColor(...REPORT.border);
  doc.roundedRect(REPORT.margin, cursor.y, cardW, cardH, 1.5, 1.5, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...REPORT.navy);
  doc.text(title, REPORT.margin + 4, cursor.y + 6.5);
  doc.setDrawColor(...REPORT.border);
  doc.line(REPORT.margin + 4, cursor.y + 9, width - REPORT.margin - 4, cursor.y + 9);

  rows.forEach((row, index) => {
    const col = index % 2;
    const line = Math.floor(index / 2);
    const x = REPORT.margin + 4 + col * colW;
    const y = cursor.y + 15 + line * rowHeight;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.2);
    doc.setTextColor(...REPORT.muted);
    doc.text(`${row.label}:`, x, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.7);
    doc.setTextColor(...REPORT.text);
    const labelWidth = doc.getTextWidth(`${row.label}: `);
    const valueLines = doc.splitTextToSize(valueOrMissing(row.value), colW - labelWidth - 8);
    doc.text(valueLines[0] || 'Not Recorded', x + labelWidth + 1.5, y);
  });

  return { ...cursor, y: cursor.y + cardH + 4 };
}

function renderClaySession(doc, record, reportData, cursor, options = {}) {
  const data = buildClayReportData(record, reportData);
  if (options.includeTitle !== false) {
    cursor = drawSectionTitle(doc, 'CLAY SHOOTING SESSION REPORT', cursor);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(...REPORT.muted);
    doc.text('Detailed Activity Record', REPORT.margin + 2, cursor.y - 5);
  }

  cursor = drawClayCompactCard(doc, 'Session Overview', [
    { label: 'Session Date', value: formatDate(record.date) },
    { label: 'Session Type', value: 'Clay Shooting' },
    { label: 'Club / Range', value: data.clubName },
    { label: 'Duration', value: data.duration || 'Not Recorded' },
    { label: 'Check-In', value: record.checkin_time || record.start_time || 'Not Recorded' },
    { label: 'Check-Out', value: record.checkout_time || record.end_time || 'Not Recorded' },
  ], cursor);

  cursor = drawClayCompactCard(doc, 'Shotgun Used', [
    { label: 'Name', value: data.shotgun.name },
    { label: 'Make', value: data.shotgun.make },
    { label: 'Model', value: data.shotgun.model },
    { label: 'Gauge', value: data.shotgun.gauge },
    { label: 'Serial', value: data.shotgun.serial_number },
    { label: 'Cartridges Fired', value: record.rounds_fired || 0 },
  ], cursor);

  cursor = drawClayCompactCard(doc, 'Cartridges / Ammunition', [
    { label: 'Brand / Name', value: record.ammunition_used },
    { label: 'Gauge', value: data.shotgun.gauge },
    { label: 'Quantity Used', value: record.rounds_fired || 0 },
    { label: 'Shot Size', value: record.shot_size },
    { label: 'Load / Weight', value: record.load_grams || record.grams },
    { label: 'Cost', value: record.cost || record.total_cost },
  ], cursor);

  if (options.separateScoreAndPhotos) {
    doc.addPage();
    cursor = drawClayPageTitle(doc, 'SCORE CARD', { y: REPORT.margin }, reportData);
  } else {
    cursor = ensureSpace(doc, cursor, data.photos.length === 0 ? 58 : 78);
    cursor = drawSectionTitle(doc, 'Score Card', cursor);
  }
  if (!data.scoreData) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(...REPORT.text);
    doc.text('No Score Card Recorded', REPORT.margin + 4, cursor.y);
    cursor.y += 10;
  } else {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(...REPORT.navy);
    doc.text('Score Summary', REPORT.margin + 2, cursor.y);
    cursor.y += 4;
    cursor = drawDataTable(doc, ['Total Targets', 'Hits', 'Missed', 'Percentage'], [[
      data.scoreData.totalTargets,
      data.scoreData.hits,
      data.scoreData.missed,
      `${data.scoreData.percentage}%`,
    ]], cursor, { widths: [52, 36, 36, 52], fontSize: 8.3, rowHeight: 9, borderColor: [155, 164, 176], lineWidth: 0.35 });

    if (data.scoreData.stands.length > 0) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(...REPORT.navy);
      doc.text('Stand Breakdown', REPORT.margin + 2, cursor.y);
      cursor.y += 4;
      cursor = drawDataTable(
        doc,
        ['Stand', 'Discipline', 'Targets', 'Hits', 'Missed', 'Score'],
        data.scoreData.stands.map((stand) => [stand.standNumber, stand.discipline, stand.targets, stand.hits, stand.missed, `${stand.hits}/${stand.targets}`]),
        cursor,
        { widths: [18, 54, 28, 22, 26, 30], leftColumns: [1], rowHeight: 9, fontSize: 8.3, borderColor: [155, 164, 176], lineWidth: 0.35 }
      );
    }
  }

  if (options.separateScoreAndPhotos) {
    doc.addPage();
    cursor = drawClayPageTitle(doc, 'PHOTOS', { y: REPORT.margin }, reportData);
    cursor = drawPhotosSection(doc, data.photos, cursor, null);
  } else {
    cursor = drawPhotosSection(doc, data.photos, cursor, 'Photos');
    if (record.notes) cursor = drawNotes(doc, record.notes, cursor);
  }
  return cursor;
}

function renderTargetSession(doc, record, reportData, cursor, options = {}) {
  const data = buildTargetReportData(record, reportData);
  const firearms = record.rifles_used?.length ? record.rifles_used : [{
    rifle_id: record.rifle_id,
    rounds_fired: record.rounds_fired,
    meters_range: record.meters_range || record.range_distance,
    ammunition_brand: record.ammunition_used,
    caliber: record.caliber,
  }];

  if (options.includeTitle !== false) {
    cursor = drawClayPageTitle(doc, 'TARGET SHOOTING SESSION REPORT', cursor, reportData);
  }

  cursor = drawClayCompactCard(doc, 'Session Overview', [
    { label: 'Session Date', value: formatDate(record.date) },
    { label: 'Session Type', value: 'Target Shooting' },
    { label: 'Club / Range', value: data.clubName },
    { label: 'Duration', value: data.duration || 'Not Recorded' },
    { label: 'Check-In', value: record.checkin_time || record.start_time || 'Not Recorded' },
    { label: 'Check-Out', value: record.checkout_time || record.end_time || 'Not Recorded' },
    ...(record.notes ? [{ label: 'Notes', value: record.notes }] : []),
  ], cursor);

  firearms.forEach((firearm, index) => {
    const rifleData = data.rifles[firearm.rifle_id] || {};
    cursor = drawClayCompactCard(doc, `Firearm #${index + 1}`, [
      { label: 'Name', value: rifleData.name || firearm.rifle_name },
      { label: 'Make', value: rifleData.make || firearm.make },
      { label: 'Model', value: rifleData.model || firearm.model },
      { label: 'Calibre', value: firearm.caliber || rifleData.caliber },
      { label: 'Serial', value: rifleData.serial_number || firearm.serial_number },
      { label: 'Rounds Fired', value: firearm.rounds_fired || 0 },
      { label: 'Range Distance', value: firearm.meters_range ? `${firearm.meters_range} m` : firearm.range_distance },
      ...(firearm.scope || rifleData.scope ? [{ label: 'Scope', value: firearm.scope || rifleData.scope }] : []),
      ...(firearm.zero_distance || rifleData.zero_distance ? [{ label: 'Zero Distance', value: firearm.zero_distance || rifleData.zero_distance }] : []),
    ], cursor);
  });

  cursor = drawClayCompactCard(doc, 'Ammunition / Ballistics', firearms.flatMap((firearm, index) => [
    ...(firearms.length > 1 ? [{ label: `Firearm #${index + 1}`, value: data.rifles[firearm.rifle_id]?.name || firearm.rifle_name || `Firearm #${index + 1}` }] : []),
    { label: 'Brand / Name', value: firearm.ammunition_brand || record.ammunition_used },
    { label: 'Bullet Type', value: firearm.bullet_type },
    { label: 'Grain Weight', value: firearm.grain },
    { label: 'Calibre', value: firearm.caliber || data.rifles[firearm.rifle_id]?.caliber || record.caliber },
    { label: 'Rounds Fired', value: firearm.rounds_fired || record.rounds_fired || 0 },
    { label: 'Reloaded / Factory', value: firearm.ammo_type || record.ammo_type },
    ...(firearm.batch_number || record.batch_number ? [{ label: 'Batch Number', value: firearm.batch_number || record.batch_number }] : []),
    ...(firearm.cost || record.cost || record.total_cost ? [{ label: 'Cost', value: firearm.cost || record.cost || record.total_cost }] : []),
    ...(firearm.powder ? [{ label: 'Powder', value: firearm.powder }] : []),
    ...(firearm.primer ? [{ label: 'Primer', value: firearm.primer }] : []),
    ...(firearm.brass ? [{ label: 'Brass', value: firearm.brass }] : []),
    ...(firearm.bullet ? [{ label: 'Bullet', value: firearm.bullet }] : []),
  ]), cursor);

  doc.addPage();
  cursor = drawClayPageTitle(doc, 'TARGET ANALYSIS', { y: REPORT.margin }, reportData);
  if (data.groups.length === 0) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(...REPORT.text);
    doc.text('No Target Analysis Recorded', REPORT.margin + 4, cursor.y);
    cursor.y += 10;
  } else {
    data.groups.forEach((group, index) => {
      const groupName = group.group_name || group.name || `Group ${index + 1}`;
      cursor = drawClayCompactCard(doc, `Group ${index + 1} — ${groupName}`, [
        { label: 'Shots', value: group.number_of_shots || group.shots },
        { label: 'Distance', value: group.distance_override || group.distance ? `${group.distance_override || group.distance} m` : null },
        { label: 'Group Size', value: group.group_size_mm ? `${group.group_size_mm} mm` : group.group_size },
        { label: 'MOA', value: Number.isFinite(Number(group.group_size_moa)) ? Number(group.group_size_moa).toFixed(2) : group.moa },
        { label: 'Accuracy Result', value: Number.isFinite(Number(group.group_size_moa)) ? `${Number(group.group_size_moa).toFixed(2)} MOA` : group.accuracy_result },
        { label: 'Notes', value: group.notes },
      ], cursor);

      const targetPhoto = getTargetGroupPhoto(group);
      if (targetPhoto) {
        cursor = ensureSpace(doc, cursor, 44);
        try {
          doc.addImage(targetPhoto, 'JPEG', REPORT.margin + 4, cursor.y, 52, 36);
          doc.link(REPORT.margin + 4, cursor.y, 52, 36, { url: targetPhoto });
        } catch (error) {
          doc.setDrawColor(...REPORT.border);
          doc.rect(REPORT.margin + 4, cursor.y, 52, 36);
          doc.setFontSize(7);
          doc.setTextColor(...REPORT.muted);
          doc.text('Image unavailable', REPORT.margin + 10, cursor.y + 19);
        }
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(...REPORT.muted);
        doc.text(`Target Photo — Group ${index + 1}`, REPORT.margin + 4, cursor.y + 41);
        cursor.y += 48;
      }
    });
  }

  doc.addPage();
  cursor = drawClayPageTitle(doc, 'PHOTOS', { y: REPORT.margin }, reportData);
  cursor = drawPhotosSection(doc, data.photos, cursor, null);
  return cursor;
}

function drawPhotosSection(doc, photos, cursor, title = 'PHOTOS') {
  if (title) cursor = drawSectionTitle(doc, title, cursor);
  if (!photos.length) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(...REPORT.text);
    doc.text('No Photos Recorded', REPORT.margin + 4, cursor.y);
    return { ...cursor, y: cursor.y + 10 };
  }

  const photoW = 40;
  const photoH = 30;
  const gap = 6;
  let x = REPORT.margin + 4;
  photos.forEach((photoUrl, index) => {
    cursor = ensureSpace(doc, cursor, photoH + 12);
    const { width } = pageMetrics(doc);
    if (x + photoW > width - REPORT.margin) {
      x = REPORT.margin + 4;
      cursor.y += photoH + 10;
      cursor = ensureSpace(doc, cursor, photoH + 12);
    }
    try {
      doc.addImage(photoUrl, 'JPEG', x, cursor.y, photoW, photoH);
      doc.link(x, cursor.y, photoW, photoH, { url: photoUrl });
    } catch (error) {
      doc.setDrawColor(...REPORT.border);
      doc.rect(x, cursor.y, photoW, photoH);
      doc.setFontSize(7);
      doc.setTextColor(...REPORT.muted);
      doc.text('Image unavailable', x + 5, cursor.y + 16);
    }
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(...REPORT.muted);
    doc.text(`Photo ${index + 1}`, x, cursor.y + photoH + 5);
    x += photoW + gap;
  });
  return { ...cursor, y: cursor.y + photoH + 13 };
}

function drawNotes(doc, notes, cursor) {
  cursor = drawSectionTitle(doc, 'NOTES', cursor);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...REPORT.text);
  doc.splitTextToSize(notes, pageMetrics(doc).width - REPORT.margin * 2 - 8).forEach((line) => {
    cursor = ensureSpace(doc, cursor, 6);
    doc.text(line, REPORT.margin + 4, cursor.y);
    cursor.y += 5;
  });
  return { ...cursor, y: cursor.y + 4 };
}

function renderDeerSession(doc, record, reportData, cursor) {
  const { rifles = {}, locations = {} } = reportData.lookups;
  const rifle = rifles[record.rifle_id] || {};
  const locationName = record.location_name || record.place_name || locations[record.location_id]?.name || locations[record.location_id]?.place_name;
  const duration = calculateDuration(record.start_time || record.checkin_time, record.end_time || record.checkout_time);

  cursor = drawInfoCard(doc, 'Session Overview', [
    { label: 'Session Date', value: formatDate(record.date) },
    { label: 'Session Type', value: 'Deer Management' },
    { label: 'Land / Location / Block', value: locationName },
    { label: 'Check-In', value: record.start_time || record.checkin_time },
    { label: 'Check-Out', value: record.end_time || record.checkout_time },
    { label: 'Duration', value: duration || 'Not Recorded' },
    { label: 'Notes', value: record.notes || 'Not Recorded' },
  ], cursor, { columns: 2, rowHeight: 14 });

  cursor = drawInfoCard(doc, 'Rifle Used', [
    { label: 'Rifle', value: joinClean([rifle.name, rifle.make, rifle.model], ' ') },
    { label: 'Make', value: rifle.make },
    { label: 'Model', value: rifle.model },
    { label: 'Calibre', value: record.caliber || rifle.caliber },
    { label: 'Serial Number', value: rifle.serial_number },
    { label: 'Rounds Fired', value: record.rounds_fired || record.total_count || record.number_shot || 0 },
  ], cursor, { columns: 2, rowHeight: 14 });

  cursor = drawInfoCard(doc, 'Ammunition', [
    { label: 'Brand / Name', value: record.ammunition_used },
    { label: 'Bullet Type', value: record.bullet_type },
    { label: 'Grain Weight', value: record.grain },
    { label: 'Calibre', value: record.caliber || rifle.caliber },
    { label: 'Rounds Fired', value: record.rounds_fired || record.total_count || record.number_shot || 0 },
    { label: 'Batch Number', value: record.batch_number },
  ], cursor, { columns: 2, rowHeight: 14 });

  cursor = drawInfoCard(doc, 'Cull / Deer Details', [
    { label: 'Species', value: record.deer_species || (record.species_list?.length ? record.species_list.map((item) => `${item.species}: ${item.count}`).join(', ') : null) },
    { label: 'Sex', value: record.sex },
    { label: 'Age Class', value: record.age_class },
    { label: 'Cull Count', value: record.total_count || record.number_shot || 0 },
    { label: 'Weight', value: record.weight || record.carcass_weight },
    { label: 'Condition', value: record.condition },
    { label: 'Shot Placement', value: record.shot_placement },
    { label: 'Inspection Notes', value: record.inspection_notes || record.gralloch_notes },
  ], cursor, { columns: 2, rowHeight: 14 });

  cursor = drawInfoCard(doc, 'GPS / Location', buildGpsLocationRows(record, locationName), cursor, { columns: 2, rowHeight: 14 });

  doc.addPage();
  cursor = drawClayPageTitle(doc, 'PHOTOS', { y: REPORT.margin }, reportData);
  cursor = drawPhotosSection(doc, normalizePhotos(record.photos || []), cursor, null);
  return cursor;
}

function drawActivityLogHeader(doc, reportData, cursor) {
  const { width } = pageMetrics(doc);
  doc.setFillColor(...REPORT.navy);
  doc.roundedRect(REPORT.margin, cursor.y, width - REPORT.margin * 2, 32, 2, 2, 'F');
  doc.setTextColor(...REPORT.white);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('SHOOTING ACTIVITY RECORD', REPORT.margin + 6, cursor.y + 11);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Firearms Usage & Attendance Log', REPORT.margin + 6, cursor.y + 18);
  doc.setFontSize(8);
  doc.text('Generated from completed shooting activity records', REPORT.margin + 6, cursor.y + 24);
  doc.setDrawColor(...REPORT.copper);
  doc.setLineWidth(1.2);
  doc.line(REPORT.margin + 6, cursor.y + 28, width - REPORT.margin - 6, cursor.y + 28);
  return { ...cursor, y: cursor.y + 40 };
}

function resolveActivityLocation(record, clubs = {}, locations = {}) {
  return record.club_name
    || record.range_name
    || record.location_name
    || record.place_name
    || record.venue_name
    || (record.club_id && clubs[record.club_id]?.name)
    || (record.location_id && (clubs[record.location_id]?.name || locations[record.location_id]?.name || locations[record.location_id]?.place_name))
    || 'Not Recorded';
}

function activityTypeLabel(record) {
  if (record.category === 'target_shooting' || record.recordType === 'target') return 'Target Shooting';
  if (record.category === 'clay_shooting' || record.recordType === 'clay') return 'Clay Shooting';
  if (record.category === 'deer_management' || record.recordType === 'deer') return 'Deer Management';
  return 'Shooting Activity';
}

function getRecordCategoryKey(record) {
  if (record.category === 'target_shooting' || record.recordType === 'target') return 'target_shooting';
  if (record.category === 'clay_shooting' || record.recordType === 'clay') return 'clay_shooting';
  if (record.category === 'deer_management' || record.recordType === 'deer') return 'deer_management';
  return 'other';
}

function getFilteredOverviewRecords(records, selectedCategory) {
  if (!selectedCategory || selectedCategory === 'all') return records;
  return records.filter((record) => getRecordCategoryKey(record) === selectedCategory || record.recordType === selectedCategory);
}

function sumRecordRounds(record) {
  const category = getRecordCategoryKey(record);
  if (category === 'target_shooting') {
    if (record.rifles_used?.length) return record.rifles_used.reduce((sum, rifle) => sum + Number(rifle.rounds_fired || 0), 0);
    return Number(record.rounds_fired || record.shots_fired || 0);
  }
  if (category === 'clay_shooting') return Number(record.rounds_fired || record.cartridges_fired || record.total_shots || 0);
  if (category === 'deer_management') return Number(record.rounds_fired || record.shots_fired || 0);
  return Number(record.rounds_fired || 0);
}

function formatRoundsByCategory(category, total) {
  if (category === 'clay_shooting') return `${total} cartridges`;
  return `${total} rounds`;
}

function getUniqueFirearmCount(records) {
  const ids = new Set();
  records.forEach((record) => {
    if (record.rifles_used?.length) record.rifles_used.forEach((rifle) => rifle.rifle_id && ids.add(rifle.rifle_id));
    [record.rifle_id, record.shotgun_id, record.firearm_id, record.weapon_id, record.gun_id].forEach((id) => id && ids.add(id));
  });
  return ids.size;
}

function buildReportSummaryRows(reportData, records) {
  const dates = records.map((record) => new Date(record.date)).filter((date) => !Number.isNaN(date.getTime()));
  const sortedDates = dates.sort((a, b) => a - b);
  const categories = [...new Set(records.map(activityTypeLabel))].filter((label) => label !== 'Shooting Activity');
  const totalRounds = records.reduce((sum, record) => sum + sumRecordRounds(record), 0);
  const firearmCount = getUniqueFirearmCount(records);
  return [
    { label: 'Report Generated', value: reportData.generatedAtLabel },
    { label: 'Total Records', value: records.length },
    { label: 'Date Range', value: sortedDates.length ? `${formatDate(sortedDates[0])} – ${formatDate(sortedDates[sortedDates.length - 1])}` : 'Not Recorded' },
    { label: 'Categories Included', value: categories.length ? categories.join(', ') : 'Not Recorded' },
    { label: 'Total Rounds / Cartridges', value: totalRounds || 'Not Recorded' },
    { label: 'Total Firearms Used', value: firearmCount || 'Not Recorded' },
  ];
}

function drawCategorySummaryTable(doc, records, cursor) {
  const categories = ['target_shooting', 'clay_shooting', 'deer_management'];
  const rows = categories.map((category) => {
    const categoryRecords = records.filter((record) => getRecordCategoryKey(record) === category);
    const total = categoryRecords.reduce((sum, record) => sum + sumRecordRounds(record), 0);
    return [activityTypeLabel({ category }), categoryRecords.length, formatRoundsByCategory(category, total)];
  }).filter((row) => row[1] > 0);

  if (rows.length === 0) return cursor;
  cursor = drawSectionTitle(doc, 'Activity Category Summary', cursor);
  return drawDataTable(doc, ['Category', 'Records', 'Rounds / Cartridges'], rows, cursor, {
    widths: [84, 36, 58],
    leftColumns: [0],
    rowHeight: 10,
    fontSize: 8.5,
  });
}

function drawCoverNote(doc, cursor) {
  cursor = drawSectionTitle(doc, 'Report Note', cursor);
  const { width } = pageMetrics(doc);
  const note = 'This report summarises completed shooting activity records entered in Shooting Records. Detailed session information is grouped by activity type on the following pages.';
  doc.setFillColor(...REPORT.soft);
  doc.setDrawColor(...REPORT.border);
  doc.roundedRect(REPORT.margin, cursor.y, width - REPORT.margin * 2, 22, 2, 2, 'FD');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.8);
  doc.setTextColor(...REPORT.text);
  doc.text(doc.splitTextToSize(note, width - REPORT.margin * 2 - 10), REPORT.margin + 5, cursor.y + 7);
  return { ...cursor, y: cursor.y + 28 };
}

function formatTimeRange(record) {
  const start = record.checkin_time || record.start_time;
  const end = record.checkout_time || record.end_time;
  if (start && end) return `${start}–${end}`;
  return start || end || 'Not Recorded';
}

function joinClean(parts, separator = ' ') {
  return parts.filter((part) => part !== null && part !== undefined && part !== '').join(separator) || 'Not Recorded';
}

function getTargetFirearms(record, rifles = {}) {
  const firearms = record.rifles_used?.length ? record.rifles_used : [{ rifle_id: record.rifle_id, rounds_fired: record.rounds_fired, ammunition_brand: record.ammunition_used, caliber: record.caliber }];
  return firearms.map((firearm) => ({ firearm, rifle: rifles[firearm.rifle_id] || {} }));
}

function formatSingleTargetValue(record, rifles, field) {
  const firearms = getTargetFirearms(record, rifles);
  if (firearms.length !== 1) return null;
  const { firearm, rifle } = firearms[0];
  if (field === 'name') return joinClean([rifle.name || firearm.rifle_name, rifle.make || firearm.make, rifle.model || firearm.model], ' ');
  if (field === 'make') return rifle.make || firearm.make || 'Not Recorded';
  if (field === 'model') return rifle.model || firearm.model || 'Not Recorded';
  if (field === 'caliber') return firearm.caliber || rifle.caliber || 'Not Recorded';
  if (field === 'serial') return rifle.serial_number || firearm.serial_number || 'Not Recorded';
  if (field === 'ammo') return joinClean([firearm.ammunition_brand || record.ammunition_used, firearm.bullet_type, firearm.grain ? `${firearm.grain}gr` : null], ' ');
  if (field === 'rounds') return firearm.rounds_fired ?? record.rounds_fired ?? 0;
  return 'Not Recorded';
}

function formatTargetFirearmList(record, rifles = {}) {
  const firearms = getTargetFirearms(record, rifles);
  if (firearms.length <= 1) return null;
  return firearms.map(({ firearm, rifle }, index) => {
    const name = joinClean([rifle.name || firearm.rifle_name, rifle.make || firearm.make, rifle.model || firearm.model], ' ');
    const caliber = firearm.caliber || rifle.caliber || 'Not Recorded';
    const serial = rifle.serial_number || firearm.serial_number || 'Not Recorded';
    const rounds = firearm.rounds_fired ?? 0;
    const ammo = joinClean([firearm.ammunition_brand, firearm.bullet_type, firearm.grain ? `${firearm.grain}gr` : null], ' ');
    return `${index + 1}. ${name} — ${caliber} — Serial: ${serial} — Rounds: ${rounds}${ammo !== 'Not Recorded' ? ` — Ammo: ${ammo}` : ''}`;
  }).join('\n');
}

function formatActivityNotes(record) {
  if (record.notes) return record.notes;
  if (record.species_list?.length) return record.species_list.map((item) => `${item.species}: ${item.count}`).join(', ');
  return 'Not Recorded';
}

function formatCoordinate(point) {
  if (!point) return null;
  const lat = point.lat ?? point.latitude;
  const lng = point.lng ?? point.longitude;
  if (lat === undefined || lng === undefined) return null;
  return `${Number(lat).toFixed(6)}, ${Number(lng).toFixed(6)}`;
}

function getGpsTrack(record) {
  return record.gps_track || record.gpsTrack || record.track || record.route_points || record.routePoints || record.gps_points || record.gpsPoints || [];
}

function getSavedDistance(record) {
  return record.distance_travelled || record.distance_traveled || record.tracking_distance || record.gps_distance || record.distance || null;
}

function buildGpsLocationRows(record, locationName) {
  const track = Array.isArray(getGpsTrack(record)) ? getGpsTrack(record) : [];
  const startPoint = track[0] || record.start_location;
  const endPoint = track.length > 0 ? track[track.length - 1] : record.end_location;
  const checkInCoords = formatCoordinate(startPoint) || formatCoordinate({ lat: record.checkin_lat || record.start_lat || record.latitude, lng: record.checkin_lng || record.start_lng || record.longitude });
  const checkOutCoords = formatCoordinate(endPoint) || formatCoordinate({ lat: record.checkout_lat || record.end_lat, lng: record.checkout_lng || record.end_lng });
  const distance = getSavedDistance(record);

  if (track.length === 0 && !checkInCoords && !checkOutCoords && !locationName) {
    return [{ label: 'Tracking Status', value: 'No GPS points saved', full: true }];
  }

  return [
    ...(locationName ? [{ label: 'Location', value: locationName, full: true }] : []),
    ...(checkInCoords ? [{ label: 'Check-In Coordinates', value: checkInCoords, full: true }] : []),
    ...(checkOutCoords ? [{ label: 'Check-Out Coordinates', value: checkOutCoords, full: true }] : []),
    { label: 'GPS Points Saved', value: track.length || '0' },
    { label: 'Distance', value: distance ? `${distance}` : 'Not recorded' },
    { label: 'Tracking Status', value: track.length > 0 ? 'Recorded' : (locationName ? 'GPS coordinates not recorded' : 'No GPS points saved'), full: true },
  ];
}

function drawCategoryTitle(doc, title) {
  const { width } = pageMetrics(doc);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...REPORT.navy);
  doc.text(title, REPORT.margin, REPORT.margin + 6);
  doc.setDrawColor(...REPORT.copper);
  doc.setLineWidth(0.8);
  doc.line(REPORT.margin, REPORT.margin + 11, width - REPORT.margin, REPORT.margin + 11);
  return { y: REPORT.margin + 22 };
}

function sectionRowsHeight(doc, rows, innerWidth) {
  const colGap = 8;
  const colW = (innerWidth - colGap) / 2;
  let height = 0;
  for (let i = 0; i < rows.length; i += 1) {
    const row = rows[i];
    if (row.full) {
      const lines = doc.splitTextToSize(valueOrMissing(row.value), innerWidth - 32);
      height += Math.max(6, lines.length * 4.2) + 2;
    } else if (i % 2 === 0) {
      const pair = rows.slice(i, i + 2);
      const rowH = Math.max(...pair.map((item) => {
        const lines = doc.splitTextToSize(valueOrMissing(item.value), colW - 30);
        return Math.max(6, lines.length * 4.2);
      }));
      height += rowH + 2;
    }
  }
  return height;
}

function drawOverviewSection(doc, section, x, y, innerWidth) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.setTextColor(...REPORT.navy);
  doc.text(section.title, x, y);
  y += 4;
  doc.setDrawColor(...REPORT.border);
  doc.setLineWidth(0.2);
  doc.line(x, y, x + innerWidth, y);
  y += 5;

  const colGap = 8;
  const colW = (innerWidth - colGap) / 2;
  section.rows.forEach((row, index) => {
    if (!row.full && index % 2 === 1) return;
    const rowPair = row.full ? [row] : section.rows.slice(index, index + 2);
    let maxRowHeight = 6;
    rowPair.forEach((item, pairIndex) => {
      const rowX = row.full ? x : x + pairIndex * (colW + colGap);
      const rowW = row.full ? innerWidth : colW;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(...REPORT.muted);
      doc.text(`${item.label}:`, rowX, y);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...REPORT.text);
      const valueX = rowX + 29;
      const valueLines = doc.splitTextToSize(valueOrMissing(item.value), rowW - 31);
      doc.text(valueLines, valueX, y);
      maxRowHeight = Math.max(maxRowHeight, valueLines.length * 4.2);
    });
    y += maxRowHeight + 2;
  });
  return y + 2;
}

function drawOverviewSessionCard(doc, title, sections, cursor) {
  const { width, height } = pageMetrics(doc);
  const cardX = REPORT.margin;
  const cardW = width - REPORT.margin * 2;
  const padding = 7;
  const innerWidth = cardW - padding * 2;
  const sectionGap = 3;
  const cardH = 13 + sections.reduce((sum, section) => sum + 10 + sectionRowsHeight(doc, section.rows, innerWidth) + sectionGap, 0) + padding;

  if (cursor.y + cardH > height - 20) {
    doc.addPage();
    cursor = { ...cursor, y: REPORT.margin };
  }

  doc.setFillColor(...REPORT.white);
  doc.setDrawColor(...REPORT.border);
  doc.setLineWidth(0.35);
  doc.roundedRect(cardX, cursor.y, cardW, cardH, 2, 2, 'FD');

  let y = cursor.y + padding;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...REPORT.navy);
  doc.text(title, cardX + padding, y);
  y += 8;

  sections.forEach((section) => {
    y = drawOverviewSection(doc, section, cardX + padding, y, innerWidth) + sectionGap;
  });

  return { ...cursor, y: cursor.y + cardH + 6 };
}

function drawTargetOverviewRecord(doc, record, reportData, cursor) {
  const { rifles = {}, clubs = {}, locations = {} } = reportData.lookups;
  const firearms = getTargetFirearms(record, rifles);
  const multiFirearmList = formatTargetFirearmList(record, rifles);
  const first = firearms[0] || { firearm: {}, rifle: {} };
  const firearm = first.firearm;
  const rifle = first.rifle;
  const duration = calculateDuration(record.checkin_time || record.start_time, record.checkout_time || record.end_time);

  return drawOverviewSessionCard(doc, `Target Shooting — ${formatDate(record.date)}`, [
    { title: 'Activity Details', rows: [
      { label: 'Club / Range', value: resolveActivityLocation(record, clubs, locations), full: true },
      { label: 'Check-In', value: record.checkin_time || record.start_time },
      { label: 'Check-Out', value: record.checkout_time || record.end_time },
      ...(duration ? [{ label: 'Duration', value: duration }] : []),
    ] },
    { title: multiFirearmList ? 'Firearms Used' : 'Firearm Used', rows: multiFirearmList ? [
      { label: 'Firearms', value: multiFirearmList, full: true },
    ] : [
      { label: 'Firearm', value: joinClean([rifle.name || firearm.rifle_name, rifle.make || firearm.make, rifle.model || firearm.model], ' '), full: true },
      { label: 'Make', value: rifle.make || firearm.make },
      { label: 'Model', value: rifle.model || firearm.model },
      { label: 'Calibre', value: firearm.caliber || rifle.caliber },
      { label: 'Serial Number', value: rifle.serial_number || firearm.serial_number },
      { label: 'Rounds Fired', value: firearm.rounds_fired ?? record.rounds_fired ?? 0 },
      { label: 'Range Distance', value: firearm.meters_range ? `${firearm.meters_range} m` : firearm.range_distance },
    ] },
    { title: 'Ammunition', rows: [
      { label: 'Brand / Name', value: firearm.ammunition_brand || record.ammunition_used, full: true },
      { label: 'Bullet Type', value: firearm.bullet_type || record.bullet_type },
      { label: 'Grain Weight', value: firearm.grain || record.grain },
      { label: 'Calibre', value: firearm.caliber || rifle.caliber || record.caliber },
      { label: 'Rounds Fired', value: firearm.rounds_fired ?? record.rounds_fired ?? 0 },
    ] },
    { title: 'GPS / Location', rows: buildGpsLocationRows(record, resolveActivityLocation(record, clubs, locations)) },
    { title: 'Notes', rows: [{ label: 'Notes', value: formatActivityNotes(record), full: true }] },
  ], cursor);
}

function drawClayOverviewRecord(doc, record, reportData, cursor) {
  const { shotguns = {}, clubs = {}, locations = {} } = reportData.lookups;
  const shotgun = shotguns[record.shotgun_id] || {};
  const duration = calculateDuration(record.checkin_time || record.start_time, record.checkout_time || record.end_time);

  return drawOverviewSessionCard(doc, `Clay Shooting — ${formatDate(record.date)}`, [
    { title: 'Activity Details', rows: [
      { label: 'Club / Range', value: resolveActivityLocation(record, clubs, locations), full: true },
      { label: 'Check-In', value: record.checkin_time || record.start_time },
      { label: 'Check-Out', value: record.checkout_time || record.end_time },
      ...(duration ? [{ label: 'Duration', value: duration }] : []),
    ] },
    { title: 'Shotgun Used', rows: [
      { label: 'Shotgun', value: joinClean([shotgun.name, shotgun.make, shotgun.model], ' '), full: true },
      { label: 'Make', value: shotgun.make },
      { label: 'Model', value: shotgun.model },
      { label: 'Gauge', value: shotgun.gauge },
      { label: 'Serial Number', value: shotgun.serial_number },
      { label: 'Cartridges Fired', value: record.rounds_fired || 0 },
    ] },
    { title: 'Cartridges / Ammunition', rows: [
      { label: 'Brand / Name', value: record.ammunition_used, full: true },
      { label: 'Gauge', value: shotgun.gauge },
      { label: 'Quantity Used', value: record.rounds_fired || 0 },
      { label: 'Shot Size', value: record.shot_size },
      { label: 'Load / Weight', value: record.load_grams || record.grams },
    ] },
    { title: 'GPS / Location', rows: buildGpsLocationRows(record, resolveActivityLocation(record, clubs, locations)) },
    { title: 'Notes', rows: [{ label: 'Notes', value: formatActivityNotes(record), full: true }] },
  ], cursor);
}

function drawDeerOverviewRecord(doc, record, reportData, cursor) {
  const { rifles = {}, locations = {} } = reportData.lookups;
  const rifle = rifles[record.rifle_id] || {};
  const duration = calculateDuration(record.start_time || record.checkin_time, record.end_time || record.checkout_time);

  return drawOverviewSessionCard(doc, `Deer Management — ${formatDate(record.date)}`, [
    { title: 'Activity Details', rows: [
      { label: 'Land / Location', value: record.location_name || record.place_name || locations[record.location_id]?.name || locations[record.location_id]?.place_name, full: true },
      { label: 'Check-In', value: record.start_time || record.checkin_time },
      { label: 'Check-Out', value: record.end_time || record.checkout_time },
      ...(duration ? [{ label: 'Duration', value: duration }] : []),
    ] },
    { title: 'Rifle Used', rows: [
      { label: 'Rifle', value: joinClean([rifle.name, rifle.make, rifle.model], ' '), full: true },
      { label: 'Make', value: rifle.make },
      { label: 'Model', value: rifle.model },
      { label: 'Calibre', value: record.caliber || rifle.caliber },
      { label: 'Serial Number', value: rifle.serial_number },
      { label: 'Rounds Fired', value: record.rounds_fired || record.total_count || record.number_shot || 0 },
    ] },
    { title: 'Cull / Species Details', rows: [
      { label: 'Species', value: record.deer_species || (record.species_list?.length ? record.species_list.map((item) => `${item.species}: ${item.count}`).join(', ') : null), full: true },
      { label: 'Sex', value: record.sex },
      { label: 'Cull Count', value: record.total_count || record.number_shot || 0 },
      { label: 'Animal Notes', value: record.animal_notes },
    ] },
    { title: 'Ammunition', rows: [
      { label: 'Brand / Name', value: record.ammunition_used, full: true },
      { label: 'Bullet Type', value: record.bullet_type },
      { label: 'Grain Weight', value: record.grain },
      { label: 'Calibre', value: record.caliber || rifle.caliber },
      { label: 'Rounds Fired', value: record.rounds_fired || record.total_count || record.number_shot || 0 },
    ] },
    { title: 'GPS / Location', rows: buildGpsLocationRows(record, record.location_name || record.place_name || locations[record.location_id]?.name || locations[record.location_id]?.place_name) },
    { title: 'Notes', rows: [{ label: 'Notes', value: formatActivityNotes(record), full: true }] },
  ], cursor);
}

function renderCategoryPage(doc, title, records, reportData, drawRecord) {
  doc.addPage();
  let cursor = drawCategoryTitle(doc, title);
  if (records.length === 0) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(...REPORT.text);
    doc.text('No records found for this category.', REPORT.margin + 2, cursor.y);
    return;
  }
  records.forEach((record) => {
    cursor = drawRecord(doc, record, reportData, cursor);
  });
}

function renderActivityLogRecords(doc, reportData, options = {}) {
  let cursor = drawActivityLogHeader(doc, reportData, { y: REPORT.margin });
  const selectedCategory = options.selectedCategory || options.category || 'all';
  const summaryRecords = getFilteredOverviewRecords(reportData.records, selectedCategory);

  cursor = drawInfoCard(doc, 'User Details', [
    { label: 'Name', value: reportData.participant.name },
    { label: 'Email', value: reportData.participant.email },
    { label: 'Date of Birth', value: reportData.participant.dateOfBirth },
    { label: 'Address', value: reportData.participant.address },
  ], cursor, { columns: 2, rowHeight: 16 });

  cursor = drawInfoCard(doc, 'Report Summary', buildReportSummaryRows(reportData, summaryRecords), cursor, { columns: 2, rowHeight: 15 });
  cursor = drawCategorySummaryTable(doc, summaryRecords, cursor);
  cursor = drawCoverNote(doc, cursor);

  const targetRecords = reportData.records.filter((record) => record.category === 'target_shooting' || record.recordType === 'target');
  const clayRecords = reportData.records.filter((record) => record.category === 'clay_shooting' || record.recordType === 'clay');
  const deerRecords = reportData.records.filter((record) => record.category === 'deer_management' || record.recordType === 'deer');

  if ((selectedCategory === 'all' && targetRecords.length) || selectedCategory === 'target_shooting' || selectedCategory === 'target') {
    renderCategoryPage(doc, 'Target Shooting', targetRecords, reportData, drawTargetOverviewRecord);
  }
  if ((selectedCategory === 'all' && clayRecords.length) || selectedCategory === 'clay_shooting' || selectedCategory === 'clay') {
    renderCategoryPage(doc, 'Clay Shooting', clayRecords, reportData, drawClayOverviewRecord);
  }
  if ((selectedCategory === 'all' && deerRecords.length) || selectedCategory === 'deer_management' || selectedCategory === 'deer') {
    renderCategoryPage(doc, 'Deer Management', deerRecords, reportData, drawDeerOverviewRecord);
  }
}

function renderRecords(doc, reportData, options = {}) {
  let cursor = { y: REPORT.margin };
  const isClayOnly = reportData.records.length > 0 && reportData.records.every((record) => record.category === 'clay_shooting' || record.recordType === 'clay');
  const isTargetOnly = reportData.records.length > 0 && reportData.records.every((record) => record.category === 'target_shooting' || record.recordType === 'target');
  const isDeerOnly = reportData.records.length > 0 && reportData.records.every((record) => record.category === 'deer_management' || record.recordType === 'deer');

  if (options.overview) {
    renderActivityLogRecords(doc, reportData, options);
    return;
  }

  if (!isClayOnly && !isTargetOnly) {
    renderActivityLogRecords(doc, reportData, options);
    return;
  }

  if (isClayOnly) {
    cursor = drawClayReportHeader(doc, reportData, cursor);
  } else if (isTargetOnly) {
    cursor = drawTargetReportHeader(doc, reportData, cursor);
  } else if (isDeerOnly) {
    cursor = drawClayPageTitle(doc, 'DEER MANAGEMENT SESSION REPORT', cursor, reportData);
  } else {
    cursor = drawHeader(doc, reportData, cursor);
    cursor = drawParticipantInfo(doc, reportData, cursor);
  }

  reportData.records.forEach((record, index) => {
    cursor = ensureSpace(doc, cursor, index === 0 ? 30 : 55);
    if (index > 0 && cursor.y > 220) {
      doc.addPage();
      cursor = { y: REPORT.margin };
      if (isClayOnly) cursor = drawClayReportHeader(doc, reportData, cursor);
      if (isTargetOnly) cursor = drawTargetReportHeader(doc, reportData, cursor);
      if (isDeerOnly) cursor = drawClayPageTitle(doc, 'DEER MANAGEMENT SESSION REPORT', cursor, reportData);
    }
    if (record.category === 'clay_shooting' || record.recordType === 'clay') {
      cursor = renderClaySession(doc, record, reportData, cursor, { includeTitle: !isClayOnly, separateScoreAndPhotos: isClayOnly });
    } else if (record.category === 'target_shooting' || record.recordType === 'target') {
      cursor = renderTargetSession(doc, record, reportData, cursor, { includeTitle: !isTargetOnly });
    } else if (record.category === 'deer_management' || record.recordType === 'deer') {
      cursor = renderDeerSession(doc, record, reportData, cursor);
    }
  });
}

export async function exportProfessionalRecordsToPdf(records, userInfo = null, fileName = 'shooting-records.pdf', rifles = {}, clubs = {}, shotguns = {}, locations = {}, targetGroups = [], clayData = {}, options = {}) {
  const userData = await getUserData(userInfo);
  const documentId = generateDocumentId();
  const reportData = buildShootingReportData(records, userData, { rifles, clubs, shotguns, locations, targetGroups, clayData }, documentId);
  const doc = createDoc();
  renderRecords(doc, reportData, options);
  addReportFooter(doc, documentId, options.overview ? reportData.generatedAtLabel : null);
  doc.save(fileName);
}

export async function getProfessionalRecordsPdfBlob(records, userInfo = null, rifles = {}, clubs = {}, shotguns = {}, locations = {}, targetGroups = [], clayData = {}, options = {}) {
  const userData = await getUserData(userInfo);
  const documentId = generateDocumentId();
  const reportData = buildShootingReportData(records, userData, { rifles, clubs, shotguns, locations, targetGroups, clayData }, documentId);
  const doc = createDoc();
  renderRecords(doc, reportData, options);
  addReportFooter(doc, documentId, options.overview ? reportData.generatedAtLabel : null);
  return doc.output('blob');
}